spring:
  output:
    ansi:
      enabled: always
  application:
    name: chat-room
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://www.qz-hotpot.xyz:3306/chat_room?charset=utf8mb4&useSSL=false&serverTimezone=UTC&characterEncoding=utf-8
    username: ENC(MMw4b/ET5WkLGYLsQGZT3Q==)
    password: ENC(Ltec45nbu2K6OFmXEZY817uzdKs8XKOo)
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
server:
  servlet:
    context-path: /cr
  port: 8888
logging:
  level:
    cn.hotpot: debug
  file: chat-room.log